baseurl                  = "https://timothyravis.github.io"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Timothy Ravis"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = "UA-67905664-2"                  # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon 02 Jan 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "wayang.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "γένοι', οἷος ἐσσὶ μαθών. Made with Hugo."

# Metadata for Open Graph and Twitter
    description          = "A new Hugo site."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Call me Tim"
    # rss                = ""

[[params.mainMenu]]
    link = "posts"
    text = "posts"

[[params.mainMenu]]
    link = "projects"
    text = "projects"

[[params.mainMenu]]
    link = "design"
    text = "''design''"

[[params.mainMenu]]
    link = "about"
    text = "who is tim?"

[imaging]
    quality = 75
